services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true   # melhora detecção de mudanças em Windows/WSL
      - WATCHPACK_POLLING=true
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
